CREATE TABLE [dbo].[AJJK_table]
(
	[AJJK_Id] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [AJJK_Name] NVARCHAR(50) NOT NULL, 
    [AJJK_Subject] NVARCHAR(50) NOT NULL, 
    [AJJK_Date] NVARCHAR(50) NOT NULL, 
    [AJJK_Description] NVARCHAR(50) NOT NULL, 
    [AJJK_Status] NVARCHAR(50) NOT NULL, 
    [AJJK_EDIT_ID] INT NOT NULL IDENTITY
)
