CREATE PROCEDURE [dbo].[ICESComSea]
	@ICESSearch nvarchar(50)
AS
BEGIN
SELECT
ICES AS ICES,
ICESIDNO AS ICESIDNO,
ICESName AS ICESName,
ICESInstitutionalEmail AS ICESInstitutionalEmail,
ICESComment  AS ICESComment
FROM ICESComments
WHERE
ICES LIKE @ICESSearch OR
ICESIDNO LIKE @ICESSearch OR
ICESName LIKE @ICESSearch OR
ICESInstitutionalEmail LIKE @ICESSearch or
ICESComment LIKE @ICESSearch
END